# Generated by Django 3.1.2 on 2022-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='retail_price_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
