# Generated by Django 3.1.2 on 2022-06-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distr_app', '0007_book_total_rental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_rental',
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
